# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "extraction.baml": "enum ExtractedEntityLabel {\n  PLACEHOLDER\n  @@dynamic\n}\n\nenum ExtractedRelationLabel {\n  PLACEHOLDER\n  @@dynamic\n}\n\nclass BAMLExtractedEntity {\n  label ExtractedEntityLabel\n  text string\n  char_start int\n  char_end int\n}\n\nclass BAMLExtractedRelation {\n  label ExtractedRelationLabel\n  source_text string\n  target_text string\n}\n\nclass BAMLExtractionResult {\n  entities BAMLExtractedEntity[]\n  relations BAMLExtractedRelation[]\n}\n\nfunction ExtractEntitiesAndRelations(chunk_text: string) -> BAMLExtractionResult {\n  client \"openai/gpt-4o-mini\"\n  prompt #\"\n    Extract every entity and relation from the text below. Use only the declared\n    entity and relation labels; do not invent new ones.\n\n    {{ _.role(\"user\") }}\n    {{ chunk_text }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
    "generators.baml": "generator target {\n  output_type \"python/pydantic\"\n  output_dir \"../\"\n  version \"0.226.1\"\n  default_client_mode \"async\"\n}\n",
    "resolution.baml": "function VerifyEntityMatch(\n  entity_a: string,\n  context_a: string,\n  entity_b: string,\n  context_b: string,\n) -> bool {\n  client \"openai/gpt-4o-mini\"\n  prompt #\"\n    Decide whether these two mentions refer to the same real-world entity. If you\n    are not confident, answer false.\n\n    Mention A: {{ entity_a }}\n    Context A: {{ context_a }}\n    Mention B: {{ entity_b }}\n    Context B: {{ context_b }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}

def get_baml_files():
    return _file_map