# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractEntitiesAndRelations(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.BAMLExtractionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntitiesAndRelations", llm_response=llm_response, mode="request")
        return typing.cast(types.BAMLExtractionResult, __result__)

    def GenerateCypherQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCypherQuery", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def VerifyEntityMatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> bool:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifyEntityMatch", llm_response=llm_response, mode="request")
        return typing.cast(bool, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractEntitiesAndRelations(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.BAMLExtractionResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractEntitiesAndRelations", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.BAMLExtractionResult, __result__)

    def GenerateCypherQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCypherQuery", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def VerifyEntityMatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> bool:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifyEntityMatch", llm_response=llm_response, mode="stream")
        return typing.cast(bool, __result__)

    