# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.BAMLExtractedEntity": types.BAMLExtractedEntity,
    "stream_types.BAMLExtractedEntity": stream_types.BAMLExtractedEntity,

    "types.BAMLExtractedRelation": types.BAMLExtractedRelation,
    "stream_types.BAMLExtractedRelation": stream_types.BAMLExtractedRelation,

    "types.BAMLExtractionResult": types.BAMLExtractionResult,
    "stream_types.BAMLExtractionResult": stream_types.BAMLExtractionResult,


    "types.ExtractedEntityLabel": types.ExtractedEntityLabel,

    "types.ExtractedRelationLabel": types.ExtractedRelationLabel,

}