# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class ExtractedEntityLabel(str, Enum):
    PLACEHOLDER = "PLACEHOLDER"

class ExtractedRelationLabel(str, Enum):
    PLACEHOLDER = "PLACEHOLDER"

# #########################################################################
# Generated classes (3)
# #########################################################################

class BAMLExtractedEntity(BaseModel):
    label: typing.Union[ExtractedEntityLabel, str]
    text: str
    char_start: int
    char_end: int
    properties: typing.Dict[str, str] = Field(description='Schema-declared property values this entity\'s type defines, keyed by\nproperty name, drawn only from what the text states. Empty object when\nnone apply. Do not invent property names or values.')

class BAMLExtractedRelation(BaseModel):
    label: typing.Union[ExtractedRelationLabel, str]
    source_text: str
    target_text: str

class BAMLExtractionResult(BaseModel):
    entities: typing.List["BAMLExtractedEntity"]
    relations: typing.List["BAMLExtractedRelation"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################


# #########################################################################
# Model rebuilds (3)
# #########################################################################
# Resolve string forward references now that every model above is defined so
# class declaration order never breaks Pydantic construction (issue #793).
# Recursive models are intentionally omitted (Pydantic resolves those lazily;
# eagerly rebuilding them can recurse).
BAMLExtractedEntity.model_rebuild()
BAMLExtractedRelation.model_rebuild()
BAMLExtractionResult.model_rebuild()
