# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
# These are exports, not used here, hence the linter is disabled
from baml_py.baml_py import FieldType, EnumValueBuilder, EnumBuilder, ClassBuilder # noqa: F401 # pylint: disable=unused-import
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["BAMLExtractedEntity","BAMLExtractedRelation","BAMLExtractionResult",]
        ), enums=set(
          ["ExtractedEntityLabel","ExtractedRelationLabel",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 2
    # #########################################################################

    @property
    def ExtractedEntityLabel(self) -> "ExtractedEntityLabelBuilder":
        return ExtractedEntityLabelBuilder(self)

    @property
    def ExtractedRelationLabel(self) -> "ExtractedRelationLabelBuilder":
        return ExtractedRelationLabelBuilder(self)


    # #########################################################################
    # Generated classes 3
    # #########################################################################

    @property
    def BAMLExtractedEntity(self) -> "BAMLExtractedEntityViewer":
        return BAMLExtractedEntityViewer(self)

    @property
    def BAMLExtractedRelation(self) -> "BAMLExtractedRelationViewer":
        return BAMLExtractedRelationViewer(self)

    @property
    def BAMLExtractionResult(self) -> "BAMLExtractionResultViewer":
        return BAMLExtractionResultViewer(self)



# #########################################################################
# Generated enums 2
# #########################################################################

class ExtractedEntityLabelAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ExtractedEntityLabel")
        self._values: typing.Set[str] = set([  "PLACEHOLDER",  ])
        self._vals = ExtractedEntityLabelValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ExtractedEntityLabelValues":
        return self._vals


class ExtractedEntityLabelBuilder(ExtractedEntityLabelAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, baml_py.EnumValueBuilder]]:
        return [(name, self._bldr.value(name)) for name in self._values]

    def add_value(self, name: str) -> baml_py.EnumValueBuilder:
        if name in self._values:
            raise ValueError(f"Value {name} already exists.")
        return self._bldr.value(name)
    

class ExtractedEntityLabelValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    def __getattr__(self, name: str) -> baml_py.EnumValueBuilder:
        if name not in self.__values:
            raise AttributeError(f"Value {name} not found.")
        return self.__bldr.value(name)

    
    @property
    def PLACEHOLDER(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("PLACEHOLDER")
    
    


class ExtractedRelationLabelAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ExtractedRelationLabel")
        self._values: typing.Set[str] = set([  "PLACEHOLDER",  ])
        self._vals = ExtractedRelationLabelValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ExtractedRelationLabelValues":
        return self._vals


class ExtractedRelationLabelBuilder(ExtractedRelationLabelAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, baml_py.EnumValueBuilder]]:
        return [(name, self._bldr.value(name)) for name in self._values]

    def add_value(self, name: str) -> baml_py.EnumValueBuilder:
        if name in self._values:
            raise ValueError(f"Value {name} already exists.")
        return self._bldr.value(name)
    

class ExtractedRelationLabelValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    def __getattr__(self, name: str) -> baml_py.EnumValueBuilder:
        if name not in self.__values:
            raise AttributeError(f"Value {name} not found.")
        return self.__bldr.value(name)

    
    @property
    def PLACEHOLDER(self) -> baml_py.EnumValueBuilder:
        return self.__bldr.value("PLACEHOLDER")
    
    



# #########################################################################
# Generated classes 3
# #########################################################################

class BAMLExtractedEntityAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("BAMLExtractedEntity")
        self._properties: typing.Set[str] = set([  "label",  "text",  "char_start",  "char_end",  "properties",  ])
        self._props = BAMLExtractedEntityProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "BAMLExtractedEntityProperties":
        return self._props


class BAMLExtractedEntityViewer(BAMLExtractedEntityAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class BAMLExtractedEntityProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def label(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("label"))
    
    @property
    def text(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("text"))
    
    @property
    def char_start(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("char_start"))
    
    @property
    def char_end(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("char_end"))
    
    @property
    def properties(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("properties"))
    
    


class BAMLExtractedRelationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("BAMLExtractedRelation")
        self._properties: typing.Set[str] = set([  "label",  "source_text",  "target_text",  ])
        self._props = BAMLExtractedRelationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "BAMLExtractedRelationProperties":
        return self._props


class BAMLExtractedRelationViewer(BAMLExtractedRelationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class BAMLExtractedRelationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def label(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("label"))
    
    @property
    def source_text(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("source_text"))
    
    @property
    def target_text(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("target_text"))
    
    


class BAMLExtractionResultAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("BAMLExtractionResult")
        self._properties: typing.Set[str] = set([  "entities",  "relations",  ])
        self._props = BAMLExtractionResultProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "BAMLExtractionResultProperties":
        return self._props


class BAMLExtractionResultViewer(BAMLExtractionResultAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class BAMLExtractionResultProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def entities(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("entities"))
    
    @property
    def relations(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("relations"))
    
    

